kind: ConfigMap
apiVersion: v1
metadata:
  name: service-core-env
  namespace: dispute-test
data:
  JVM_OPTS: "-Xms512m -Xmx1024m"
  bangying_datasource_url: "jdbc:mysql://host:port/database?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false"
  bangying_datasource_name: "user" # mysql 用户名