apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dispute-test
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: nginx
      protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: dispute-test
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx
          containerPort: 8001
        env:
          - name: TZ
            value: Asia/Shanghai
        resources:
          requests:
            memory: 50M
          limits:
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
          - name: nginx-wechat-test
            mountPath: "/home/wwwroot/"
            # subPath: wechat
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf            
      volumes:
        - name: nginx-wechat-test
          persistentVolumeClaim:
            claimName: nginx-dispute-test
        - name: nginx-config
          configMap:
                name: nginx-config-2020   