apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /grafana-devops-dispute/
    server: xxxxxxxx.cn-beijing.nas.aliyuncs.com       # ----replace------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops
  name: devops-grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: devops
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: devops
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - {key: devops-node, operator: In, values: ["beijing-node"]}
      containers:
        - name: grafana
          image: grafana/grafana:7.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana
              containerPort: 3000
          securityContext:
            runAsUser: 0
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: 20M
            limits:
              memory: 500M
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: grafana-devops
              mountPath: "/var/lib/grafana"
              #subPath: grafana-devops-dispute       
      volumes:
        - name: grafana-devops
          persistentVolumeClaim:
            claimName: devops-grafana-pvc