apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: devops
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: devops
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grafana
              containerPort: 3000
          securityContext:
            runAsUser: 0
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: 50M
            limits:
              memory: 1Gi
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: grafana-devops
              mountPath: "/var/lib/grafana"
              subPath: grafana-devops-dispute       
      volumes:
        - name: grafana-devops
          persistentVolumeClaim:
            claimName: grafana