apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: nexus
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  serviceName: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      nodeName: cn-beijing.172.30.10.209
      containers:
      - name: nexus
        image: sonatype/nexus3
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: nexus
          containerPort: 8081
        env:
          - name: TZ
            value: Asia/Shanghai
        resources:
          requests:
            memory: 1024M
          limits:
            memory: 2000M
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
          subPath: nexus3-devops-dispute
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus3