apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: nexus
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  serviceName: nexus
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - {key: devops-node, operator: In, values: ["beijing-node"]}
      containers:
      - name: nexus
        image: sonatype/nexus3
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: nexus
          containerPort: 8081
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: INSTALL4J_ADD_VM_PARAMS
            value: "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=1024m"
        resources:
          requests:
            memory: 1024M
          limits:
            memory: 2000M
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
          subPath: nexus3-devops-dispute
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus3