apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-nexus3-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #回收策略
  nfs:
    path: /nexus3-devops-dispute/
    server: xxxxxxxx.cn-beijing.nas.aliyuncs.com       # ----replace------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops
  name: devops-nexus3-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: nexus
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nexus
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - {key: devops-node, operator: In, values: ["beijing-node"]}
      containers:
      - name: nexus
        image: sonatype/nexus3
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: nexus
          containerPort: 8081
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: INSTALL4J_ADD_VM_PARAMS
            value: "-Xms256m -Xmx512m -XX:MaxDirectMemorySize=1024m"
        resources:
          requests:
            memory: 500M
          limits:
            memory: 2000M
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
          # subPath: nexus3-devops-dispute
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: devops-nexus3-pvc