apiVersion: v1
kind: Service
metadata:
  labels:
    app: jumpserver
  name: jumpserver-ssh
  namespace: devops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    nodePort: 22222
    port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: jumpserver
  sessionAffinity: None
  type: NodePort
