apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-jenkins-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /jenkins-devops-dispute/
    server: xxxxxxx.cn-beijing.nas.aliyuncs.com       # ----replace------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops
  name: devops-jenkins-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - {key: devops-node, operator: In, values: ["beijing-node"]}
      containers:
      - name: jenkins
        image: chaiyd/jenkins:2.249.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: jenkins
          containerPort: 8080
        - name: jenkins-slave
          containerPort: 50000
        env:
          - name: TZ
            value: Asia/Shanghai
        resources:
          requests:
            memory: 300M
          limits:
            memory: 3Gi
        volumeMounts:
          - name: jenkins-pvc
            mountPath: "/var/jenkins_home"
            # subPath: jenkins-devops-dispute
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: kubectl
            mountPath: /usr/bin/kubectl
      volumes:
        - name: jenkins-pvc
          persistentVolumeClaim:
            claimName: devops-jenkins-pvc
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock
        - name: kubectl
          hostPath:
              path: /usr/bin/kubectl