apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
              - {key: devops-node, operator: In, values: ["beijing-node"]}
      containers:
      - name: jenkins
        image: chaiyd/jenkins:2.249.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - name: jenkins
          containerPort: 8080
        - name: jenkins-slave
          containerPort: 50000
        env:
          - name: JAVA_OPTS
            value: -Xmx2048m -XshowSettings:vm -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Duser.timezone=Asia/Shanghai
        resources:
          requests:
            memory: 300M
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
          - name: jenkins-pvc
            mountPath: "/var/jenkins_home"
            # subPath: jenkins-devops-dispute
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: kubectl
            mountPath: /usr/bin/kubectl
      volumes:
        - name: jenkins-pvc
          persistentVolumeClaim:
            claimName: devops-jenkins-pvc
        - name: docker-sock
          hostPath:
              path: /var/run/docker.sock
        - name: kubectl
          hostPath:
              path: /usr/bin/kubectl