apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-jenkins-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #回收策略
  nfs:
    path: /jenkins-devops-dispute/
    server: xxxxxxx.cn-beijing.nas.aliyuncs.com       # ----replace------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: devops
  name: devops-jenkins-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi