apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-oap
  namespace: devops
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: skywalking-oap
      release: skywalking
  template:
    metadata:
      labels:
        app: skywalking-oap
        release: skywalking
    spec:
      nodeSelector:
       nodetype: wedesign
      containers:
        - name: skywalking-oap
          image: apache/skywalking-oap-server:6.6.0-es6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11800
              name: grpc
            - containerPort: 12800
              name: rest
          env:
            - name: JAVA_OPTS
              value: -Xms256M -Xmx512M
            # 挂载配置文件时,从volume载入配置 否则由于挂载config时 会与镜像内路径冲突 报错read only filesystem 
            # - name: SW_L0AD_CONFIG_FILE_FROM_VOLUME
            #   value: "true"
            # - name: SW_STORAGE
            #   value: elasticsearch
            # - name: SW_STORAGE_ES_CLUSTER_NODES
            #   value: "192.168.78.136:9200"
            # - name: SW_CLUSTER
            #   value: kubernetes
            # - name: SW_CLUSTER_K8S_NAMESPACE
            #   value: skywalking
            # - name: SW_SERVICE_MESH_OFFSET_MAX_FILE_SIZE
            #   value: "200"
            # - name: SW_RECEIVER_BUFFER_DATA_MAX_FILE_SIZE
            #   value: "800"
            # - name: SW_RECEIVER_BUFFER_FILE_CLEAN_WHEN_RESTART
            #   value: "true"
            # - name: SKYWALKING_oap_UID
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.uid
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: devops
  labels:
    service: skywalking-oap
spec:
  ports:
    - port: 12800
      name: rest
    - port: 11800
      name: grpc
  selector:
    app: skywalking-oap